name: de_helper
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cupertino_icons: ^1.0.8
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.3
  json_annotation: ^4.9.0
  mobile_scanner: ^7.1.4
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  uuid: ^4.5.2
  excel: ^2.1.0
  share_plus: ^7.0.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  drift_dev: ^2.30.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
